# @package _group_
- name: SGD
  params: null
  
  # Configuration for the REST of the network (Backbone ImageNet)
  kwargs:
    lr: 0.02
    momentum: 0.9
    weight_decay: 0.002
    
  bias_kwargs:
    weight_decay: 0.0

  # --- NEW: Specific Modules ---
  modules:
    - name: "backbone.conv1"
      kwargs:
        lr: 0.2
        momentum: 0.9
        weight_decay: 0.002

  # Schedulers (Unchanged)
  scheduler_on_step:
      name: warmcos
      kwargs:
          total_steps: 2820      # 60 Ã©poques * 47 batches
          warmup_steps: 100
  scheduler_on_epoch: null
  scheduler_on_val: null