# @package _group_
- name: SGD
  params: null
  
  # Configuration for the REST of the network (Backbone ImageNet)
  kwargs:
    lr: 0.02
    momentum: 0.9
    weight_decay: 0.0005
    
  bias_kwargs:
    weight_decay: 0.0

  # --- NEW: Specific Modules ---
  modules:
    - name: "backbone.conv1"       # Target: "backbone.conv1.", "lh_backbone.conv1.", etc.
      kwargs:
        lr: 0.2            # LR x10 for these layers
        momentum: 0.9      # We repeat momentum (mandatory in group)
        weight_decay: 0.0005

  # Schedulers (Unchanged)
  scheduler_on_step:
      name: warmcos
      kwargs:
          total_steps: 940 # 20 epochs * 47 batches
          warmup_steps: 100
  scheduler_on_epoch: null
  scheduler_on_val: null