# @package _group_
- name: SGD
  params: null
  kwargs:
    lr: 0.02
    momentum: 0.0
    weight_decay: 0.0005
    nesterov: False
  bias_kwargs:
    weight_decay: 0.0

  # IMPORTANT : Rien dans epoch
  scheduler_on_epoch:

  # TOUT dans step pour le warmcos
  scheduler_on_step:
      name: warmcos
      kwargs:
          total_steps: 940      # 20 epochs * ~47 batches
          warmup_steps: 100     # Valeur "en dur" du repo officiel
  scheduler_on_val: