# @package _group_
name: RetrievalNet
freeze_batch_norm: False
freeze_pos_embedding: False
kwargs:
  backbone_name: dino
  dino_backbone: 'dinov2_vits14'
  embed_dim: 384
  norm_features: False
  without_fc: True
  with_autocast: True
  pretrained: True