# @package _group_
name: RetrievalNet
freeze_batch_norm: False
freeze_pos_embedding: False
kwargs:
  backbone_name: mtwavenet
  embed_dim: 2048
  norm_features: False
  without_fc: True
  with_autocast: True
  attention: True
  decom_level: 1
  wave: haar
  feature_size: 512
  attention_type: cbam
  coarse_only: True
<<<<<<< HEAD
  num_classes: 64
  pretrained: False
=======
  num_classes: ${dataset.num_classes}
  pretrained: True
>>>>>>> e27955aa3f83cca34ab99b45ce2239a3e8786fd8
