# @package _group_
name: RetrievalNet
freeze_batch_norm: False
freeze_pos_embedding: False
kwargs:
  backbone_name: multi_dino_v3
  dino_backbone: 'dinov3_vits16'
  weights: 'c:\These\data\models\dinov3_vits16_pretrain_lvd1689m-08c60483.pth'
  dino_version: 'dinov3'
  embed_dim: 384
  norm_features: False
  without_fc: True
  with_autocast: True
  pretrained: True
  branches: [0, 1, 2, 3]