# @package _group_
name: RetrievalNet
freeze_batch_norm: True
freeze_pos_embedding: False
kwargs:
  backbone_name: resnet_ce
  embed_dim: 2048
  norm_features: False
  without_fc: True
  with_autocast: True
  num_classes: 200
  pretrained: True
  dropout: 0.5
