# @package _group_
name: RetrievalNet
freeze_batch_norm: False
freeze_pos_embedding: False
kwargs:
  backbone_name: resnet50
  embed_dim: 2048
  norm_features: False
  without_fc: False
  with_autocast: True
  pretrained: False
