# @package _group_
name: RetrievalNet
freeze_batch_norm: False
freeze_pos_embedding: False
kwargs:
  backbone_name: wresnet
  embed_dim: 512
  norm_features: False
  without_fc: False
  with_autocast: True
  attention: False
  decom_level: 1
  wave: haar
  feature_size: 512
  attention_type: eca
  num_classes: 200