# @package _group_
train:
  Resize:
    size: 224
  RandomHorizontalFlip:
    p: 0.5
  SWTTransform:
    level: 4
    wavelet: 'haar'

test:
  Resize:
    size: 224
  SWTTransform:
    level: 4
    wavelet: 'haar'