# @package _group_
train:
  Resize:
    size: 512
  RandomResizedCrop:
    scale: [0.16, 1]
    ratio: [0.75, 1.33]
    size: 448
  ColorJitter:
    brightness: 0.25
    contrast: 0.25
    saturation: 0.25
    hue: 0.
  RandomHorizontalFlip:
    p: 0.5
  ToTensor: {}
  Normalize:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
  CustomTransform:
    decompose_levels: 1
    basis: haar
    coarse_only: True
    ll_only: True

test:
  Resize:
    size: 512
  CenterCrop:
    size: 448
  ToTensor: {}
  Normalize:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
  CustomTransform:
    decompose_levels: 1
    basis: haar
    coarse_only: True
    ll_only: True