# @package _group_
train:
  Resize:
    size: 256
  RandomResizedCrop:
    scale: [0.16, 1]
    ratio: [0.75, 1.33]
    size: 224
  ColorJitter:
    brightness: 0.25
    contrast: 0.25
    saturation: 0.25
    hue: 0.
  RandomHorizontalFlip:
    p: 0.5
  SWTTransform:
    level: 1
    wavelet: 'haar'

test:
  Resize:
    size: 256
  CenterCrop:
    size: 224
  SWTTransform:
    level: 1
    wavelet: 'haar'