# @package _group_
train:
  Resize:
    size: [576, 576]
  RandomResizedCrop:
    scale: [0.16, 1]
    ratio: [0.75, 1.33]
    size: 512
  RandomHorizontalFlip:
    p: 0.5
  ToTensor: {}
  Normalize:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
  CustomTransform:
    decompose_levels: 1
    basis: haar
    coarse_only: False

test:
  Resize:
    size: [576, 576]
  CenterCrop:
    size: 512
  ToTensor: {}
  Normalize:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
  CustomTransform:
    decompose_levels: 1
    basis: haar
    coarse_only: False
