train:
  RandomResizedCrop:
    size: 512             # Haute résolution (Sub-bands = 256px)
    scale: [0.4, 1.0]     # Scale corrigé (Oiseau visible)
    ratio: [1.0, 1.0]     # Carré strict
  ColorJitter:
    brightness: 0.4
    contrast: 0.4
    saturation: 0.4
  RandomHorizontalFlip:
    p: 0.5
  ToTensor: {}
  Normalize:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
  # LE MANQUANT : Découpe l'image en 4 pour le réseau
  CustomTransform:
    decompose_levels: 1
    basis: haar
    coarse_only: False

test:
  Resize:
    size: 576
  CenterCrop:             # CenterCrop pour une évaluation stable
    size: 512
  ToTensor: {}
  Normalize:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
  # LE MANQUANT EN TEST AUSSI
  CustomTransform:
    decompose_levels: 1
    basis: haar
    coarse_only: False