# @package _group_
train:
  # Grayscale:
<<<<<<< HEAD
  #   num_output_channels: 3
  ToTensor: {}
  # Normalize:
  #   mean: [0.485, 0.456, 0.406]
  #   std: [0.229, 0.224, 0.225]
  CustomTransform:
    decompose_levels: 1
    basis: haar
    coarse_only: True
=======
  #   num_output_channels:
>>>>>>> e27955aa3f83cca34ab99b45ce2239a3e8786fd8
  Resize:
    size: [256, 256]
  RandomResizedCrop:
    scale: [0.16, 1]
    ratio: [0.75, 1.33]
    size: 224
  RandomHorizontalFlip:
    p: 0.5
<<<<<<< HEAD
  
test:
  # Grayscale:
  #   num_output_channels: 3
  ToTensor: {}
  # Normalize:
  #   mean: [0.485, 0.456, 0.406]
  #   std: [0.229, 0.224, 0.225]
=======
  ToTensor: {}
  Normalize:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
  CustomTransform:
    decompose_levels: 1
    basis: haar
    coarse_only: True
  
test:
  Resize:
    size: [256, 256]
  CenterCrop:
    size: [224, 224]
  # Grayscale:
  #   num_output_channels: 3
  ToTensor: {}
  Normalize:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
>>>>>>> e27955aa3f83cca34ab99b45ce2239a3e8786fd8
  CustomTransform:
    decompose_levels: 1
    basis: haar
    coarse_only: True

<<<<<<< HEAD
  Resize:
    size: [256, 256]
  CenterCrop:
    size: [224, 224]
=======
  
>>>>>>> e27955aa3f83cca34ab99b45ce2239a3e8786fd8
