# @package _group_
- name:  MultiEmbeddingLoss
  weight: 1.0
  kwargs:
    loss_name: 'SupAP'
    weights: [0.75, 0.75, 0.75, 0.75, 2.0]
    tau: 0.01
    rho: 100.0
    offset: 1.44
    delta: 0.05
- name:  MultiEmbeddingLoss
  weight: 1.0
  kwargs:
    loss_name: 'CalibrationLoss'
    weights: [0.75, 0.75, 0.75, 0.75, 2.0]
    pos_margin: 0.9
    neg_margin: 0.6
