# @package _group_
- name:  MultiCrossEntropyLoss
  weight: 1.0
  kwargs:
<<<<<<< HEAD
    weights: [1.0, 1.0, 1.0, 1.0]
=======
    weights: [1, 1, 1, 1]
    label_smoothing: 0.1
>>>>>>> e27955aa3f83cca34ab99b45ce2239a3e8786fd8
