# @package _group_
- name: CalibrationLoss
  weight: 1.0
  kwargs:
    pos_margin: 0.9
    neg_margin: 0.6

- name: SupAP
  weight: 1.0
  kwargs:
    tau: 0.01
    rho: 100.0
    offset: 1.44
    delta: 0.05
- name: QuantizationLoss
  weight: 0.1 # Poids faible recommandé (entre 0.001 et 0.01)
  kwargs:
    target_value: 1.0
    step_type: 'multi'  # 'linear' ou 'multi'
    warmup_step: True  # Nombre d'itérations de warmup pour le
    starting_weight: 0.001  # Poids initial pour le multi-step
    alpha: 10  # Facteur de réduction pour le multi-step
    steps: [10, 20, 30]  # Étapes pour le multi-step (en itérations)