# @package _group_
name: Cub200Dataset
kwargs:
  data_dir: C:\These\Incremental Learning\Code Icarl\icarl-pytorch\data\CUB_200_2011

sampler:
  name: RandomSampler
  kwargs:
    batch_size: 128
num_classes: 200